name = "MyFirstPackage"
uuid = "2d4f5cef-648f-45ce-b04e-926846312ee5"
authors = ["Daly E. Gutierrez <daly.gutierrez@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
